'use client';
import {use,useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
type Game={id:string;game_type:string;board:number[];turn:number;status:string;winner:number|null;player1_token:string;player2_token:string|null};
const lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function win(b:number[],p:number){return lines.some(line=>line.every(i=>b[i]===p))}
export default function TicTacToe({params}:{params:Promise<{id:string}>}){const {id:raw}=use(params);const id=raw.toUpperCase();const [g,setG]=useState<Game|null>(null);const [me,setMe]=useState(0);const [err,setErr]=useState('');const [copyText,setCopyText]=useState('COPY INVITE LINK');
useEffect(()=>{let live=true;async function init(){let t=localStorage.getItem(`gianx-games:${id}`);if(!t){t=crypto.randomUUID();localStorage.setItem(`gianx-games:${id}`,t)}const {data,error}=await supabase.from('games').select('*').eq('id',id).single();if(error||!data||data.game_type!=='tic-tac-toe'){setErr('Game not found.');return}let game=data as Game;let role=t===game.player1_token?1:t===game.player2_token?2:0;if(!role&&!game.player2_token){const {data:joined,error:je}=await supabase.rpc('join_game',{game_id:id,join_token:t});if(je){if(live)setErr(`Could not join game: ${je.message}`);return}if(joined){const row=Array.isArray(joined)?joined[0]:joined;if(row){game=row as Game;role=t===game.player1_token?1:t===game.player2_token?2:0}}}if(live){setG(game);setMe(role)}}init();const ch=supabase.channel(`game-${id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'games',filter:`id=eq.${id}`},p=>setG(p.new as Game)).subscribe();return()=>{live=false;supabase.removeChannel(ch)}},[id]);
const message=useMemo(()=>{if(!g)return '';if(g.status==='waiting')return 'WAITING FOR A FRIEND';if(g.status==='won')return g.winner===me?'YOU WIN':'YOU LOSE';if(g.status==='draw')return 'DRAW';if(!me)return 'GAME IN PROGRESS';return g.turn===me?'YOUR TURN':"THEIR TURN"},[g,me]);
async function play(i:number){if(!g||g.status!=='playing'||g.turn!==me||!me||g.board[i])return;const b=[...g.board];b[i]=me;const won=win(b,me),draw=!won&&b.every(Boolean);await supabase.from('games').update({board:b,turn:me===1?2:1,status:won?'won':draw?'draw':'playing',winner:won?me:null}).eq('id',id).eq('turn',me).eq('status','playing')}
async function rematch(){if(!g)return;await supabase.from('games').update({board:Array(9).fill(0),turn:g.winner===1?2:1,status:g.player2_token?'playing':'waiting',winner:null}).eq('id',id)}
async function copy(){try{await navigator.clipboard.writeText(location.href);setCopyText('LINK COPIED');setTimeout(()=>setCopyText('COPY INVITE LINK'),1600)}catch{setCopyText('COPY THIS PAGE URL')}}
if(err)return <main className="shell"><section className="panel"><h1>Could not open game.</h1><p className="sub">{err}</p><a href="/" style={{color:'white'}}>Back to Gianx Games</a></section></main>;
return <main className="gameShell"><header className="gameTop"><a href="/" className="logo" style={{color:'inherit',textDecoration:'none'}}>GIANX GAMES.</a><span className="code">GAME {id}</span></header><section className="game">{!g?<div className="waiting">Loading game…</div>:<><div className="gameName">TIC TAC TOE</div><h1 className="status">{message}</h1><div className="statusSub">{g.status==='waiting'?'Send the invite link to player two.':me?`You are ${me===1?'X':'O'}.`:'Spectating'}</div><div className="tttBoard" aria-label="Tic tac toe board">{g.board.map((v,i)=><button key={i} aria-label={`Square ${i+1}`} className={`tttCell ${v===1?'cross':v===2?'nought':''}`} onClick={()=>play(i)} disabled={g.turn!==me||g.status!=='playing'||!!v}>{v===1?'×':v===2?'○':''}</button>)}</div><div className="players"><span><b className="symbol">×</b> PLAYER 1</span><span><b className="symbol">○</b> PLAYER 2</span></div><div className="actions"><button className="secondary" onClick={copy}>{copyText}</button><button className="primary" onClick={rematch} disabled={g.status!=='won'&&g.status!=='draw'}>PLAY AGAIN</button></div>{!me&&g.player2_token&&<div className="small">Both player seats are occupied. You are viewing this game.</div>}</>}</section></main>}
