'use client';
import {use, useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
type Game={id:string;game_type:string;board:number[];turn:number;status:string;winner:number|null;player1_token:string;player2_token:string|null};
function win(b:number[],p:number){for(let r=0;r<6;r++)for(let c=0;c<7;c++){if(b[r*7+c]!==p)continue;if(c<=3&&[1,2,3].every(i=>b[r*7+c+i]===p))return true;if(r<=2&&[1,2,3].every(i=>b[(r+i)*7+c]===p))return true;if(c<=3&&r<=2&&[1,2,3].every(i=>b[(r+i)*7+c+i]===p))return true;if(c>=3&&r<=2&&[1,2,3].every(i=>b[(r+i)*7+c-i]===p))return true}return false}
export default function GamePage({params}:{params:Promise<{id:string}>}){const {id:raw}=use(params);const id=raw.toUpperCase();const [g,setG]=useState<Game|null>(null);const [me,setMe]=useState(0);const [err,setErr]=useState('');const [copyText,setCopyText]=useState('COPY INVITE LINK');
useEffect(()=>{let live=true;async function init(){let t=localStorage.getItem(`gianx-games:${id}`);if(!t){t=crypto.randomUUID();localStorage.setItem(`gianx-games:${id}`,t)}const {data,error}=await supabase.from('games').select('*').eq('id',id).single();if(error||!data){setErr('Game not found.');return}let game=data as Game;if(game.game_type!=='four'){setErr('Game not found.');return}let role=t===game.player1_token?1:t===game.player2_token?2:0;if(!role&&!game.player2_token){const {data:joined,error:je}=await supabase.rpc('join_game',{game_id:id,join_token:t});if(je){if(live)setErr(`Could not join game: ${je.message}`);return}if(joined){const row=Array.isArray(joined)?joined[0]:joined;if(row){game=row as Game;role=t===game.player1_token?1:t===game.player2_token?2:0}}}if(live){setG(game);setMe(role)}}init();const ch=supabase.channel(`game-${id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'games',filter:`id=eq.${id}`},p=>setG(p.new as Game)).subscribe();return()=>{live=false;supabase.removeChannel(ch)}},[id]);
const message=useMemo(()=>{if(!g)return '';if(g.status==='waiting')return 'WAITING FOR A FRIEND';if(g.status==='won')return g.winner===me?'YOU WIN':'YOU LOSE';if(g.status==='draw')return 'DRAW';if(!me)return 'GAME IN PROGRESS';return g.turn===me?'YOUR TURN':"THEIR TURN"},[g,me]);
async function drop(col:number){if(!g||g.status!=='playing'||g.turn!==me||!me)return;const b=[...g.board];let row=-1;for(let r=5;r>=0;r--)if(b[r*7+col]===0){row=r;break}if(row<0)return;b[row*7+col]=me;const won=win(b,me),draw=!won&&b.every(Boolean);await supabase.from('games').update({board:b,turn:me===1?2:1,status:won?'won':draw?'draw':'playing',winner:won?me:null}).eq('id',id).eq('turn',me).eq('status','playing')}
async function rematch(){if(!g)return;await supabase.from('games').update({board:Array(42).fill(0),turn:g.winner===1?2:1,status:g.player2_token?'playing':'waiting',winner:null}).eq('id',id)}
async function copy(){try{await navigator.clipboard.writeText(location.href);setCopyText('LINK COPIED');setTimeout(()=>setCopyText('COPY INVITE LINK'),1600)}catch{setCopyText('COPY THIS PAGE URL')}}
if(err)return <main className="shell"><section className="panel"><h1>Game not found.</h1><p className="sub">Check the game code or create a new game.</p><a href="/" style={{color:'white'}}>Back to Gianx Games</a></section></main>;
return <main className="gameShell"><header className="gameTop"><a href="/" className="logo" style={{color:'inherit',textDecoration:'none'}}>FOUR.</a><span className="code">GAME {id}</span></header><section className="game">{!g?<div className="waiting">Loading game…</div>:<><h1 className="status">{message}</h1><div className="statusSub">{g.status==='waiting'?'Send the invite link to player two.':me?`You are ${me===1?'red':'yellow'}.`: 'Spectating'}</div><div className="boardWrap"><div className="board" aria-label="Four in a row board">{g.board.map((v,i)=><button key={i} aria-label={`Column ${(i%7)+1}`} className={`cell ${v===1?'red':v===2?'yellow':''} ${g.turn===me&&g.status==='playing'?'playable':''}`} onClick={()=>drop(i%7)} disabled={g.turn!==me||g.status!=='playing'}/>)}</div></div><div className="players"><span><i className="dot red"/>PLAYER 1</span><span><i className="dot yellow"/>PLAYER 2</span></div><div className="actions"><button className="secondary" onClick={copy}>{copyText}</button><button className="primary" onClick={rematch} disabled={g.status!=='won'&&g.status!=='draw'}>PLAY AGAIN</button></div>{!me&&g.player2_token&&<div className="small">Both player seats are occupied. You are viewing this game.</div>}</>}</section></main>}
